name: fresko_app
description: "Fresko app project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # ----- PAQUETES DE FIREBASE (COMENTADOS TEMPORALMENTE) -----
  # firebase_core: ^3.1.0
  # cloud_firestore: ^5.0.0
  # ----- FIN PAQUETES DE FIREBASE -----

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # O la versión que tuvieras

flutter:
  uses-material-design: true

  assets:
    - assets/images/fresko.jpg
    - assets/images/Freskly.jpg